# dataset
dataset_name: armband
dataset_path: ../dataset/MyoArmbandDataset
gestures: [1, 2, 3, 4, 5, 6, 7]
num_channels: 8

# subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 
# 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
# sessions: [1, 2, 3]
# trials: [1, 2, 3, 4]

# pretrain on all train subjects, train on test subjects' train session, test on test subjects' test session
# Male: 1-12, 20-34
# Female: 13-19, 35-36
loocv: False

pretrain:
  subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  sessions: [1]
  trials: [1, 2, 3, 4]
  window_size: 52 # 260ms
  window_step: 52 #
  batch_size: 16
  num_epochs: 100

train:
  subjects: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]
  train_sessions: [1]
  test_sessions: [2, 3]
  train_trials: [1, 2, 3, 4]  # 100% train data
  test_trials: [1, 2, 3, 4]
  window_size: 52 # 260ms
  window_step: 5 # 25ms
  batch_size: 32
  num_epochs: 100


# train
optimizer: Adam
base_lr: 0.01
weight_decay: 0.0001
milestones: [5, 10, 25]
gamma: 0.1


# model
model_dir: results

# logger
log_dir: logs

# tensorboard
tb_dir: runs


