# dataset
dataset_name: capgmyo-dbb
dataset_path: ../dataset/capgmyo/dbb
gestures: [1, 2, 3, 4, 5, 6, 7, 8]
num_channels: 128

# for every subject, pretrain on trials of all two sessions of the rest subjects, train on train_trails of its own
loocv: True

pretrain:
  subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  sessions: [1, 2]
  trials: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  window_size: 150 # 150ms
  window_step: 150 # 150ms
  batch_size: 128
  num_epochs: 100

train:
  subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  train_sessions: [1, 2]
  test_sessions: [1, 2]
  train_trials: [1, 3, 5, 7, 9] # 100% train data
  test_trials: [2, 4, 6, 8, 10]
  window_size: 150 # 150ms
  window_step: 70 # 70ms
  batch_size: 16
  num_epochs: 100


# train

optimizer: Adam
base_lr: 0.01
weight_decay: 0.0001
milestones: [5, 10, 25]
gamma: 0.1


# model
model_dir: results

# logger
log_dir: logs

# tensorboard
tb_dir: runs


