# dataset
dataset_name: myo
dataset_path: ../dataset/MyoDataset
gestures: [1, 2, 3, 4, 5, 6, 7, 8, 9]
num_channels: 8

loocv: True

pretrain:
  subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  sessions: [1, 2]
  trials: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  window_size: 52 # 260ms
  window_step: 52 # 260ms
  batch_size: 52
  num_epochs: 100

train:
  subjects: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  train_sessions: [1, 2]
  test_sessions: [1, 2]
  train_trials: [1, 3, 5, 7, 9]  # 100% train data
  test_trials: [2, 4, 6, 8, 10]
  window_size: 52 # 260ms
  window_step: 5 # 25ms
  batch_size: 32
  num_epochs: 100


# train
optimizer: Adam
base_lr: 0.01
weight_decay: 0.0001
milestones: [5, 10, 25]
gamma: 0.1


# model
model_dir: results

# logger
log_dir: logs

# tensorboard
tb_dir: runs


